spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc
    url: jdbc:mysql://106.14.119.166:33306/arcgis?characterEncoding=utf-8&useSSL=false
#   hikari:
#      maximum-pool-size: 5
  jpa:
    show-sql: true
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
mybatis:
  type-aliases-package: com.engine.zjut.entity
server:
  port: 8080

#server:
 # servlet:
  #  context-path: /arcgis